---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.yolvo.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov5
  template:
    metadata:
      labels:
        app: yolov5
    spec:
      containers:
        - name: {{ .Values.yolvo.name }}
          image: {{ .Values.yolvo.image }}
          command: ["python", "watch_and_detect.py"]
          volumeMounts:
            - mountPath: /app/input
              name: yolov5-volume
              subPath: input
            - mountPath: /app/output
              name: yolov5-volume
              subPath: output
      volumes:
        - name: yolov5-volume
          persistentVolumeClaim:
            claimName: yolov5-pvc
        - name: run-volume
          emptyDir: {}


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yolov5-pv
spec:
  capacity:
    storage: {{ .Values.yolvo.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/yolov5-data


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolov5-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.yolvo.storage }}


---
apiVersion: v1
kind: Service
metadata:
  name: yolov5-service
spec:
  selector:
    app: yolov5
  ports:
    - name: yolvo-http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target }}


staging
