name: Kubernetes Dev Cluster Setup

on:
  push:
    branches:
      - develop

jobs:
  setup-k8s-cluster:
    runs-on: ubuntu-latest
    name: Setup Kubernetes Master + Worker (KinD)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker
      uses: docker-practice/actions-setup-docker@v1

    - name: Install KinD
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create a Kubernetes Cluster with 1 Master and 1 Worker
      run: |
        cat <<EOF > kind-config.yaml
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
        - role: worker
        EOF

        kind create cluster --config kind-config.yaml --name object-detection-dev

    - name: Verify Nodes
      run: |
        kubectl get nodes
