name: Helmfile Deployment

on:
  workflow_run:
    workflows: ["Kubernetes Cluster Setup"]  # must match the name in actions.yaml
    types:
      - completed

jobs:
  deploy-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Run Helmfile and Show Pods
    runs-on: [self-hosted, master]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run helmfile sync
        run: |
          cd ./helm
          echo "Running helmfile sync..."
          helmfile sync

      - name: Show Running Pods
        run: |
          echo "Showing running pods..."
          kubectl get pods -A
